### ISSUE TITLE
large scale 1-halo term

### ISSUE THREAD

**Issue by steven-murray** [alexander-mead/HMcode-old#3]
I just thought I'd ask another question, because I can't seem to find any info on this.

What happens to the 1-halo term at large scales? In your code, you only go down to say k=1e-3, but if you go further down, the 1-halo term remains constant while the 2-halo term is a power law that decreases with decreasing k. At some point (1e-5 or so from memory) they cross so that the 1-halo term is dominant, which is of course completely ridiculous.

At this point, my solution to this is a bit ad hoc -- I find r ~ pi/k, then the corresponding mass for this r, then set this as the minimum mass of the integration. At low r, the minimum mass is so large that the integral is 0, so it just truncates the power. Problem is, this occurs at a scale which affects the transition region power, and introduces a 10-20% deviation from your code. My solution to this is just to adjust the rmin so that it is r = pi/k/10, which just moves the truncation further down. But of course, this is complete rubbish. 

Do you know of any _actual_ solutions to this?

**Comment by alexander-mead** [comment]
Hi Steven,

Yes, as you say, if you go to low enough k the standard one-halo overtakes
linear theory, which is clearly absurd.

There is some discussion of this here:
http://arxiv.org/pdf/astro-ph/0206508v1.pdf (Section 4.4, page 45). A short
summary is that this absurdity is linked to the fact that one considers
only positive contributions to the density perturbation when deriving the
standard form of the one-halo term. For example, haloes are considered
while voids are not. This means that certain constraints on \delta that
should be satisfied are not, for example the average value of \delta is not
zero. In the power spectrum this translates into the constant 'shot noise'
at large scales, which has been bothering you. In the 3D correlation
function this translates into a non-zero spherical average.

As far as I know there is no recognised solution to this problem with the
halo model. In my work I introduced some ad-hoc damping to suppress the
term at large scales, but this lacks a real physical motivation. I would
suggest that your solution is a bad idea if it adversely affects the
transition region (where the halo model already performs particularly
poorly).

I hope this helps.

Cheers,
Alex

**Comment by steven-murray** [comment]
Ah yes, I see. Thanks for that. I'll have a think about the best way to counter it.

Cheers,
Steven
